//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public string BookTitle { get; set; }
        public int BookYear { get; set; }
        public int ISBN { get; set; }
        public Nullable<int> StudentId { get; set; }
        public int AuthorID { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Student Student { get; set; }
    }
}
